@prefix deps:  <http://ontologi.es/doap-deps#> .

<http://purl.org/NET/cpan-uri/dist/Acme-RunDoc/project>
	deps:runtime-requirement         [ deps:on "autodie"^^deps:CpanId ];
	deps:runtime-requirement         [ deps:on "Module::Runtime"^^deps:CpanId ];
	deps:runtime-requirement         [ deps:on "Text::Extract::Word"^^deps:CpanId ];
	deps:test-requirement            [ deps:on "Test::More 0.61"^^deps:CpanId ].

